#!/bin/sh
set -eu

: "${RELEASE_MANIFEST:?RELEASE_MANIFEST is required}"
: "${RELEASE_ID:?RELEASE_ID is required}"
: "${GIT_SHA:?GIT_SHA is required}"
: "${LUMI_SERVER_IMAGE:?LUMI_SERVER_IMAGE is required}"
: "${LUMI_WEB_IMAGE:?LUMI_WEB_IMAGE is required}"

case "$RELEASE_ID" in
  ''|[!A-Za-z0-9]*|*[!A-Za-z0-9._-]*) echo "unsafe RELEASE_ID" >&2; exit 2 ;;
esac
case "$GIT_SHA" in
  *[!0-9a-f]*|'') echo "GIT_SHA must be lowercase hexadecimal" >&2; exit 2 ;;
esac
[ "${#GIT_SHA}" -eq 40 ] || { echo "GIT_SHA must be a full 40-character SHA" >&2; exit 2; }

docker_cmd=${DOCKER:-docker}
build_timestamp=${BUILD_TIMESTAMP:-$(date -u "+%Y-%m-%dT%H:%M:%SZ")}

image_repository() {
  image=$1
  case "$image" in
    *@sha256:*) printf '%s\n' "${image%@sha256:*}" ;;
    *)
      prefix=${image%/*}
      name=${image##*/}
      case "$name" in
        *:*) printf '%s/%s\n' "$prefix" "${name%%:*}" ;;
        *) printf '%s\n' "$image" ;;
      esac
      ;;
  esac
}

resolve_image() {
  image=$1
  case "$image" in
    *@sha256:*) printf '%s\n' "$image"; return ;;
  esac
  digest=$($docker_cmd buildx imagetools inspect --format '{{json .Manifest.Digest}}' "$image" 2>/dev/null | tr -d '"') || digest=
  [ -n "$digest" ] && [ "$digest" != null ] || { echo "Could not resolve digest for $image" >&2; exit 1; }
  printf '%s@%s\n' "$(image_repository "$image")" "$digest"
}

server_image=$(resolve_image "$LUMI_SERVER_IMAGE")
web_image=$(resolve_image "$LUMI_WEB_IMAGE")

mkdir -p "$(dirname "$RELEASE_MANIFEST")"
temporary="$RELEASE_MANIFEST.tmp.$$"
trap 'rm -f "$temporary"' EXIT INT TERM
{
  echo "# Generated by make release-manifest. Do not edit on the server."
  printf 'LUMI_RELEASE_ID=%s\n' "$RELEASE_ID"
  printf 'LUMI_RELEASE_SHA=%s\n' "$GIT_SHA"
  printf 'LUMI_RELEASE_AT=%s\n' "$build_timestamp"
  printf 'LUMI_SERVER_IMAGE=%s\n' "$server_image"
  printf 'LUMI_WEB_IMAGE=%s\n' "$web_image"
} > "$temporary"
mv "$temporary" "$RELEASE_MANIFEST"
trap - EXIT INT TERM
printf 'Wrote %s\n' "$RELEASE_MANIFEST"
