#!/bin/sh
set -eu

manifest=${1:?release manifest path is required}
expected_release=${2:-}

test -f "$manifest" || { echo "missing release manifest: $manifest" >&2; exit 2; }

release=
sha=
created_at=
server_image=
web_image=

while IFS= read -r line || [ -n "$line" ]; do
  case "$line" in
    '# Generated by make release-manifest. Do not edit on the server.') ;;
    LUMI_RELEASE_ID=*)
      test -z "$release" || { echo "duplicate LUMI_RELEASE_ID" >&2; exit 2; }
      release=${line#LUMI_RELEASE_ID=}
      ;;
    LUMI_RELEASE_SHA=*)
      test -z "$sha" || { echo "duplicate LUMI_RELEASE_SHA" >&2; exit 2; }
      sha=${line#LUMI_RELEASE_SHA=}
      ;;
    LUMI_RELEASE_AT=*)
      test -z "$created_at" || { echo "duplicate LUMI_RELEASE_AT" >&2; exit 2; }
      created_at=${line#LUMI_RELEASE_AT=}
      ;;
    LUMI_SERVER_IMAGE=*)
      test -z "$server_image" || { echo "duplicate LUMI_SERVER_IMAGE" >&2; exit 2; }
      server_image=${line#LUMI_SERVER_IMAGE=}
      ;;
    LUMI_WEB_IMAGE=*)
      test -z "$web_image" || { echo "duplicate LUMI_WEB_IMAGE" >&2; exit 2; }
      web_image=${line#LUMI_WEB_IMAGE=}
      ;;
    *) echo "unsupported release manifest line" >&2; exit 2 ;;
  esac
done < "$manifest"

case "$release" in
  ''|[!A-Za-z0-9]*|*[!A-Za-z0-9._-]*) echo "unsafe LUMI_RELEASE_ID" >&2; exit 2 ;;
esac
if [ -n "$expected_release" ] && [ "$release" != "$expected_release" ]; then
  echo "release identity mismatch" >&2
  exit 2
fi

case "$sha" in *[!0-9a-f]*|'') echo "invalid LUMI_RELEASE_SHA" >&2; exit 2 ;; esac
[ "${#sha}" -eq 40 ] || { echo "LUMI_RELEASE_SHA must be a full Git SHA" >&2; exit 2; }

case "$created_at" in
  [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]Z) ;;
  *) echo "invalid LUMI_RELEASE_AT" >&2; exit 2 ;;
esac

validate_image() {
  image=$1
  repository=$2
  case "$image" in
    "$repository"@sha256:*) digest=${image#"$repository"@sha256:} ;;
    *) echo "image must use $repository with a digest" >&2; exit 2 ;;
  esac
  case "$digest" in *[!0-9a-f]*|'') echo "invalid image digest" >&2; exit 2 ;; esac
  [ "${#digest}" -eq 64 ] || { echo "image digest must contain 64 hexadecimal characters" >&2; exit 2; }
}

validate_image "$server_image" ghcr.io/zaryalabs/lumi-server
validate_image "$web_image" ghcr.io/zaryalabs/lumi-web
